// <auto-generated />
using System;
using FortniteDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortniteDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825051839_AddMatchesAndGameModes")]
    partial class AddMatchesAndGameModes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FortniteDashboard.Models.GameMode", b =>
                {
                    b.Property<int>("GameModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GameModeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GameModes");

                    b.HasData(
                        new
                        {
                            GameModeId = 1,
                            Code = "SOLO",
                            Description = "100 players individual battle royale mode",
                            IsActive = true,
                            MaxPlayers = 100,
                            Name = "Battle Royale Solo"
                        },
                        new
                        {
                            GameModeId = 2,
                            Code = "DUOS",
                            Description = "50 teams of 2 players",
                            IsActive = true,
                            MaxPlayers = 100,
                            Name = "Battle Royale Duos"
                        },
                        new
                        {
                            GameModeId = 3,
                            Code = "SQUADS",
                            Description = "25 teams of 4 players",
                            IsActive = true,
                            MaxPlayers = 100,
                            Name = "Battle Royale Squads"
                        },
                        new
                        {
                            GameModeId = 4,
                            Code = "ZB_SOLO",
                            Description = "Tactical combat without building mechanics",
                            IsActive = true,
                            MaxPlayers = 100,
                            Name = "Zero Build Solo"
                        },
                        new
                        {
                            GameModeId = 5,
                            Code = "RANKED_BR",
                            Description = "Competitive skill-based ranked queue",
                            IsActive = true,
                            MaxPlayers = 100,
                            Name = "Ranked Battle Royale"
                        });
                });

            modelBuilder.Entity("FortniteDashboard.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eliminations")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameModeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameModeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Placement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("GameModeId");

                    b.HasIndex("PlayerId", "PlayedAt");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            Accuracy = 34.5m,
                            Assists = 3,
                            DamageDealt = 1420,
                            Deaths = 0,
                            Eliminations = 8,
                            GameModeId = 5,
                            GameModeName = "Ranked Battle Royale",
                            IsWin = true,
                            Placement = 1,
                            PlayedAt = new DateTime(2026, 2, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            PlayerId = 1,
                            Score = 2100
                        },
                        new
                        {
                            MatchId = 2,
                            Accuracy = 29.0m,
                            Assists = 0,
                            DamageDealt = 980,
                            Deaths = 1,
                            Eliminations = 5,
                            GameModeId = 1,
                            GameModeName = "Battle Royale Solo",
                            IsWin = false,
                            Placement = 3,
                            PlayedAt = new DateTime(2026, 2, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            PlayerId = 1,
                            Score = 1450
                        },
                        new
                        {
                            MatchId = 3,
                            Accuracy = 21.0m,
                            Assists = 1,
                            DamageDealt = 410,
                            Deaths = 1,
                            Eliminations = 2,
                            GameModeId = 4,
                            GameModeName = "Zero Build Solo",
                            IsWin = false,
                            Placement = 12,
                            PlayedAt = new DateTime(2026, 2, 18, 9, 30, 0, 0, DateTimeKind.Utc),
                            PlayerId = 2,
                            Score = 680
                        });
                });

            modelBuilder.Entity("FortniteDashboard.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FortniteUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredGameMode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("FortniteUsername")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Bio = "Competitive Fortnite player focusing on late-game rotations and tournament play.",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FortniteUsername = "Ninja_Pro",
                            Game = "Fortnite",
                            PreferredGameMode = "Ranked Battle Royale",
                            Team = "FaZe Clan",
                            UserId = 2
                        },
                        new
                        {
                            PlayerId = 2,
                            Bio = "Zero Build specialist and aim practitioner.",
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FortniteUsername = "Bucey_FTW",
                            Game = "Fortnite",
                            PreferredGameMode = "Zero Build Solo",
                            Team = "Team Liquid",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("FortniteDashboard.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedAction")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("RecommendationId");

                    b.HasIndex("PlayerId", "CreatedDate");

                    b.ToTable("Recommendations");

                    b.HasData(
                        new
                        {
                            RecommendationId = 1,
                            Category = "Combat Efficiency",
                            CreatedDate = new DateTime(2026, 2, 20, 15, 31, 0, 0, DateTimeKind.Utc),
                            MetricName = "K/D Ratio",
                            PlayerId = 1,
                            RecommendationText = "Excellent K/D ratio (4.00)! You are consistently winning trades.",
                            RecommendedAction = "Keep maintaining height advantage during late-game box fights.",
                            Severity = "Low"
                        },
                        new
                        {
                            RecommendationId = 2,
                            Category = "Late Game Conversion",
                            CreatedDate = new DateTime(2026, 2, 18, 10, 1, 0, 0, DateTimeKind.Utc),
                            MetricName = "Win Rate",
                            PlayerId = 2,
                            RecommendationText = "Your win rate is 6.67%. You are reaching mid-game but struggling in final circles.",
                            RecommendedAction = "Practice early rotations to secure high ground in moving storm zones.",
                            Severity = "High"
                        });
                });

            modelBuilder.Entity("FortniteDashboard.Models.Stats", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AvgDamage")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("AvgPlacement")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eliminations")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KDRatio")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PerformanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatId");

                    b.HasIndex("PlayerId", "RecordedAt");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            StatId = 1,
                            Accuracy = 28.5m,
                            AvgDamage = 450.0m,
                            AvgPlacement = 8.2m,
                            Deaths = 38,
                            Eliminations = 145,
                            KDRatio = 3.82m,
                            MatchesPlayed = 50,
                            PerformanceScore = 84.5m,
                            PlayerId = 1,
                            RecordedAt = new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SyncedUsername = "Ninja_Pro",
                            WinRate = 24.0m,
                            Wins = 12
                        },
                        new
                        {
                            StatId = 2,
                            Accuracy = 31.2m,
                            AvgDamage = 520.0m,
                            AvgPlacement = 6.4m,
                            Deaths = 47,
                            Eliminations = 188,
                            KDRatio = 4.00m,
                            MatchesPlayed = 65,
                            PerformanceScore = 89.0m,
                            PlayerId = 1,
                            RecordedAt = new DateTime(2026, 2, 20, 15, 30, 0, 0, DateTimeKind.Utc),
                            SyncedUsername = "Ninja_Pro",
                            WinRate = 27.69m,
                            Wins = 18
                        },
                        new
                        {
                            StatId = 3,
                            Accuracy = 19.8m,
                            AvgDamage = 280.0m,
                            AvgPlacement = 18.5m,
                            Deaths = 28,
                            Eliminations = 42,
                            KDRatio = 1.50m,
                            MatchesPlayed = 30,
                            PerformanceScore = 61.2m,
                            PlayerId = 2,
                            RecordedAt = new DateTime(2026, 2, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            SyncedUsername = "Bucey_FTW",
                            WinRate = 6.67m,
                            Wins = 2
                        });
                });

            modelBuilder.Entity("FortniteDashboard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fortnitedashboard.local",
                            IsActive = true,
                            Name = "System Administrator",
                            PasswordHash = "AQAAAAIAAYagAAAAEGA3xfnYZUgLokiDTlliblDQFgXUr5S5vFVLG07eYtH1EFPnNK1lRiL7GLA7JEO9Dw==",
                            Role = "Administrator"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ninja@esports.local",
                            IsActive = true,
                            Name = "Ninja_Pro",
                            PasswordHash = "AQAAAAIAAYagAAAAELNIfSfWiix3RC2DW7ndoaO9nMRvKWQXwvGEDVsmgdVjRoCGmalP6VeeVghjj/tzQQ==",
                            Role = "Player"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bucey@esports.local",
                            IsActive = true,
                            Name = "Bucey_FTW",
                            PasswordHash = "AQAAAAIAAYagAAAAEJO3m7sriDoUCh3CZp/uglbLksxCZMbb3qZrJ0SVHe6x9mzrgB9nWJyHeNzHe0v/7g==",
                            Role = "Player"
                        });
                });

            modelBuilder.Entity("FortniteDashboard.Models.Match", b =>
                {
                    b.HasOne("FortniteDashboard.Models.GameMode", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FortniteDashboard.Models.Player", "Player")
                        .WithMany("Matches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMode");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FortniteDashboard.Models.Player", b =>
                {
                    b.HasOne("FortniteDashboard.Models.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("FortniteDashboard.Models.Player", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FortniteDashboard.Models.Recommendation", b =>
                {
                    b.HasOne("FortniteDashboard.Models.Player", "Player")
                        .WithMany("Recommendations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FortniteDashboard.Models.Stats", b =>
                {
                    b.HasOne("FortniteDashboard.Models.Player", "Player")
                        .WithMany("StatsHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FortniteDashboard.Models.Player", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Recommendations");

                    b.Navigation("StatsHistory");
                });

            modelBuilder.Entity("FortniteDashboard.Models.User", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
